#here we using inheritance means nothing but getting properties from parent class to child class its like code reusabilty
class student():
      # video functionality watching
    def watch_videos(self):
        print("="*50)
        print("Functionality For Watching Videos")
        print("W")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print("="*50)
class video_admin(student):
     # video functionality adding
    def add_videos(self):
        print("="*50)
        print("Functionality For Adding Videos")
        print("A")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print("="*50) 
class super_admin(video_admin):
     # video functionality deleting
    def delete_videos(self):
        print("="*50)
        print("Functionality For Deleting Videos")
        print("D")
        print("e")
        print("l")
        print("e")
        print("t")
        print("e")
        print("v")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print(".")
        print("="*50) 
print("student user")
stu_obj=student()
stu_obj.watch_videos()
print("videoadmin user")
vidadm_obj=video_admin()
vidadm_obj.watch_videos()
vidadm_obj.add_videos()
print("superadmin user ")
super_obj=super_admin()
super_obj.add_videos()
super_obj.watch_videos()
super_obj.delete_videos()
